<a href="https://colab.research.google.com/github/KGF2/DeepLearningAmateur/blob/Test/FrozenLakeQTable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# FROzen lake Q-table

!pip install -q sklearn
import numpy as np
import gym
import random
import time
from IPython.display import clear_output 

#setting up the environment
env = gym.make("FrozenLake-v0")

#initializing q-table
action_space_size = env.action_space.n
state_space_size = env.observation_space.n
q_table = np.zeros((state_space_size, action_space_size))
print(env.action_space, env.observation_space)
print(action_space_size, state_space_size)
print(q_table)

Discrete(4) Discrete(16)
4 16
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [0]:
#algorithm parameters
num_episodes = 5
max_steps_per_episode = 6

learning_rate = 0.1 # alpha
discount_rate = 0.99 # gamma

exploration_rate = 0.5
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

rewards_all_episodes = []

In [0]:
for episodes in range (num_episodes):
  
  state = env.reset()
  max_steps_per_episode = 0
  rewards_current_episode = 0
  done = False

  for steps in range (max_steps_per_episode):
    exploration_rate_threshold = random.uniform(0,1)
    print (exploration_rage_threshold)
    if exploration_rate > exploration_rate_threshold:
      action = np.argmax(q_table[state,:])
    else:
      action = env.action_space.sample()

    new_state, reward, done, info = env.step(action)
    q_table[state,action] = q_table[state,action] + reward*np.max(q_table[new_state,:])
    state = new_state
    rewards_current_episode += reward
    print(new_state, state, action, reward, rewards_current_episode)
    #print(q_table)
  if done == True:
    break
rewards_all_episodes.append(rewards_current_episode)
 

In [4]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output 

#setting up the environment
env = gym.make("FrozenLake-v0")

#initializing q-table
action_space_size = env.action_space.n
state_space_size = env.observation_space.n
q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

#algorithm parameters
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1 # alpha
discount_rate = 0.99 # gamma

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

rewards_all_episodes = []

# complete q-learning algorithm where training takes place

for episode in range (num_episodes):
    
    state = env.reset() # resetting the state of the env
    done = False # to keep track of whether episode is finished or not
    rewards_current_episode = 0 # to keep track of rewards in current episode
    
    for step in range(max_steps_per_episode): # everyting that happens in each time-step within each episode
        
        # exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0,1) # choosing a random number between 0 to 1
        
        if exploration_rate_threshold > exploration_rate : # in this if-else block agent's action will be choosen
            action = np.argmax(q_table[state,:]) # agent will exploit the env and hence chose the action that has highest Q-value in the current state
        else:
            action = env.action_space.sample() # agent will explore the env and sample an action, randomly
                
        new_state, reward, done, info = env.step(action) # we take the choosen action by calling step on the env object, and pass the action to it. 
        # step returns a tuple containing all the above 4 variable values.
        # print("action", action, state, new_state, reward, done)

        # update q-table for Q(s,a)
        q_table[state, action] = ((1-learning_rate) * q_table[state, action]) + (learning_rate * (reward + discount_rate * (np.max(q_table[new_state,:]))))
        # new q-value for the state-action pair in LHS is a weighted sum of old value and learned value ie, 
        # q(s,a) = [(1-alpha) * q(s,a)] + [(alpha * q(s', a'))]
        #print("np.max(q_table[new_state is ...", np.max(q_table[new_state,:]), learning_rate, discount_rate, reward)
        
        state = new_state # updating the current state to new state
        rewards_current_episode += reward # adding reward obtained from this step, to that of the rewards in current episode
        
        if done == True: # to check if agent stepped in the Hole of reached the Goal
            break
            
    # Exploration rate decay, exponential decay after each episode 
    exploration_rate = min_exploration_rate + ((max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode))
    
    rewards_all_episodes.append(rewards_current_episode) # append list of rewards from current episode, to that of all episodes
    
# calculate and print average rewards per 1000 episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/5000)
count = 5000
#print("**********************Average reward per 1000 episodes********************\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/5000)))
    count += 5000
    
# Print updated Q-table
print("\n\n**********************Updated Q-TABLE ********************\n")
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
5000 :  0.3763999999999912
10000 :  0.6693999999999589


**********************Updated Q-TABLE ********************

[[0.55518748 0.51662382 0.52324627 0.52414767]
 [0.37663298 0.32809961 0.41130668 0.51063308]
 [0.420557   0.43474533 0.3851635  0.48767427]
 [0.21435339 0.32026624 0.28483754 0.46716346]
 [0.56762964 0.5439071  0.4360251  0.30565113]
 [0.         0.         0.         0.        ]
 [0.22799794 0.21323504 0.39546059 0.13851528]
 [0.         0.         0.         0.        ]
 [0.47804917 0.47291674 0.38636734 0.60578268]
 [0.36190543 0.63630907 0.31073583 0.44065767]
 [0.66756142 0.42705466 0.19400574 0.29914897]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.47646803 0.6618502  0.76963

In [6]:
# test / play
for episode in range(3):
  state = env.reset()
  done = False
  print("*********** EPISODE : ", episode+1, "************ \n\n\n\n")
  time.sleep(2)

  for steps in range(max_steps_per_episode):
    clear_output(wait=True)
    env.render()
    time.sleep(3)

    action = np.argmax(q_table[state,:])
    new_state, reward, done, info = env.step(action)

    if done:
      clear_output(wait=True)
      env.render()
      if reward==1:
        print("GOAL REACHED :)")
      else:
        print("Dead!!! :'(")
      time.sleep(3)
      clear_output(wait=True)
      break

    state = new_state

env.close()




  (Down)
SFFF
FHFH
FFFH
HFFG
GOAL REACHED :)
